name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: scr
          root_file: cv_english.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: scr
          root_file: cv_nederlands.tex
